################################################################################
# site.{property} settings
baseurl: ""
exclude: ['_local']
################################################################################
# my solarized theme
name: "superjamie.github.io"
title: "superjamie.github.io"
description: "Insert witty tagline"
url: "https://superjamie.github.io"

author_bio: "C, Linux, Vim, DOS. Australia. he/him"
author_github: "superjamie"
author_instagram: "msdosfloppy"
#author_mastodon_url: "https://fosstodon.org/@suprjami"
#author_twitter: "suprjami"

permalink: /:year/:month/:day/:title
paginate: 5

plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-relative-links
  - jekyll-seo-tag
  - jemoji
################################################################################
# jekyll-feed
author: Jamie Bainbridge
feed:
  path: /feed.atom
################################################################################
# https://github.com/benbalter/jekyll-relative-links
relative_links:
  enabled:     true
  collections: true
################################################################################
# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
social:
  name: Jamie Bainbridge
  links:
    - https://github.com/superjamie
#   - https://fosstodon.org/@suprjami

