################################################################################
# site.x settings
baseurl: ""
exclude: ['_local']
################################################################################
# my solarized theme
name: "superjamie.github.io"
title: "superjamie.github.io"
description: "Insert witty tagline"
url: "https://superjamie.github.io"

author_bio: "Linux, C, DOS, etc. Australia. he/him"
author_github: "superjamie"
author_instagram: "msdosfloppy"
author_mastodon_url: "https://fosstodon.org/suprjami"
author_twitter: "suprjami"

permalink: /:year/:month/:day/:title
paginate: 5

plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-relative-links
  - jemoji
################################################################################
# jekyll-feed
author: Jamie Bainbridge
feed:
  path: /feed.atom
################################################################################
# https://github.com/benbalter/jekyll-relative-links
relative_links:
  enabled:     true
  collections: true
################################################################################
