################################################################################
# site.x settings
baseurl: ""
exclude: ['_local']
################################################################################
# my solarized theme
name: "superjamie.github.io"
title: "superjamie.github.io"
description: "Insert witty tagline"
url: "https://superjamie.github.io"

author_bio: "Linux, C, DOS, etc. Australia. he/him"
author_github: "superjamie"
author_instagram: "msdosfloppy"
author_mastodon_url: "https://fosstodon.org/suprjami"
author_twitter: "suprjami"

permalink: /:year/:month/:day/:title
paginate: 5

plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-relative-links
  - jekyll-seo-tag
  - jemoji
################################################################################
# jekyll-feed
author: Jamie Bainbridge
feed:
  path: /feed.atom
################################################################################
# https://github.com/benbalter/jekyll-relative-links
relative_links:
  enabled:     true
  collections: true
################################################################################
# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
tagline: "Linux, C, DOS, etc."
# logo doesn't seem to do anything?
logo: "/assets/images/snes-buttons-rounded-256px.png"
og:image: "/assets/images/snes-buttons-rounded-256px.png"
# author
social:
  name: Jamie Bainbridge
  links:
    - https://github.com/superjamie
    - https://fosstodon.org/@suprjami
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/images/snes-buttons-rounded-256px.png"
      height: 256
      width: 256
# generates an exerpt from blogposts, no need to
# override tagline/description with something like
# {{ post.content | strip_html | truncatewords: 10 }}
