source "https://rubygems.org"

# if things occasionally break, try:
#  bundle update github-pages

gem "github-pages", group: :jekyll_plugins

#group :jekyll_plugins do
#  gem "jekyll-coffeescript"
#  gem "jekyll-default-layout"
#  gem "jekyll-gist"
#  gem "jekyll-github-metadata"
#  gem "jekyll-optional-front-matter"
#  gem "jekyll-paginate"
#  gem "jekyll-readme-index"
#  gem "jekyll-titles-from-headings"
#  gem "jekyll-relative-links"
#  gem "jekyll-feed"
#end

# jekyll-remote-theme wants this
gem "webrick"

